# Generated by Django 5.1.7 on 2025-03-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_rename_meal_meal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
