# Generated by Django 5.1.7 on 2025-03-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='personal',
            field=models.BooleanField(default=False),
        ),
    ]
