# Generated by Django 5.1.7 on 2025-03-31 07:55

from django.db import migrations, models
import datetime

def migrate_dates(apps, schema_editor):
    date = datetime.date(2024, 1, 1)

    History = apps.get_model("history", "History")
    for history in History.objects.all():
        history.date = date
        history.save()

        date = date + datetime.timedelta(days=1)

class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_dates)
    ]
